FROM node:20-alpine

RUN apk add --no-cache openssl git

WORKDIR /app

RUN npm install -g pnpm

COPY backend/package.json backend/pnpm-lock.yaml ./
COPY backend/prisma ./prisma/

RUN pnpm install --no-frozen-lockfile

COPY backend/ .
# Debug temporal
RUN ls node_modules | grep typescript

RUN pnpm exec tsc --outDir dist

EXPOSE 3000

CMD ["sh", "-c", "pnpm exec prisma migrate deploy && node dist/src/app.js"]