'use client'

import { useDeferredValue, useMemo, useRef, useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import type { UseQueryResult } from '@tanstack/react-query'
import { AlertTriangle, CheckCircle2, ChevronLeft, ChevronRight, Download, FileSpreadsheet, Plus, Search, Upload } from 'lucide-react'
import clsx from 'clsx'
import { auth } from '@/lib/auth'
import { clientsApi, collectionsApi } from '@/lib/api'
import type { Client, CollectionPayment, CollectionSummary, PaginatedResult, Receivable, RecurringCharge } from '@/types'
import { formatDate, formatMoney, getErrorMessage, isPositiveDecimal } from '@/lib/format'
import { EmptyState, ErrorState, LoadingState, PageFrame, PageHeader, SectionPanel, StatusPill } from '@/components/romez/OperationalUI'

import { RECEIVABLE_LABELS, FREQUENCY_LABELS } from '@/lib/collection-labels'
import { PaymentSummaryButton } from '@/components/romez/PaymentSummaryButton'

type View = 'receivables' | 'payments' | 'plans' | 'import'
type ImportPreviewRow = { rowNumber: number; type: 'RECEIVABLE' | 'PAYMENT'; ruc?: string; description?: string; amount?: string; currency: string; errors: string[] }
type ImportPreview = { rows: ImportPreviewRow[]; total: number; valid: number; invalid: number; committed: number }
const PAGE_SIZE = 25

function formatImportAmount(row: ImportPreviewRow) {
  if (!row.amount) return '—'
  if (!/^[A-Z]{3}$/.test(row.currency)) return `${row.currency || 'MONEDA'} ${row.amount}`
  return formatMoney(row.amount, row.currency)
}

function paraguayBusinessDate() {
  const parts = new Intl.DateTimeFormat('en-US', { timeZone: 'America/Asuncion', year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(new Date())
  const part = (type: Intl.DateTimeFormatPartTypes) => parts.find((item) => item.type === type)?.value ?? ''
  return `${part('year')}-${part('month')}-${part('day')}`
}

const BUSINESS_DATE = paraguayBusinessDate()
const RECEIVABLE_FORM = { companyId: '', description: 'Honorarios contables', periodKey: BUSINESS_DATE.slice(0, 7), currency: 'PYG', amount: '', dueDate: '', reference: '' }
const PAYMENT_FORM = { companyId: '', currency: 'PYG', amount: '', paidAt: BUSINESS_DATE, method: 'TRANSFERENCIA', reference: '', notes: '' }
const PLAN_FORM = { companyId: '', name: 'Honorarios mensuales', amount: '', currency: 'PYG', frequency: 'MONTHLY' as const, dayOfMonth: '10', startDate: BUSINESS_DATE }

export default function CollectionsPage() {
  const queryClient = useQueryClient()
  const fileRef = useRef<HTMLInputElement | null>(null)
  const role = auth.get()?.role
  const canManage = role === 'owner' || role === 'admin'
  const canWrite = Boolean(role && role !== 'viewer')
  const [view, setView] = useState<View>('receivables')
  const [search, setSearch] = useState('')
  const [status, setStatus] = useState('')
  const [receivablesPage, setReceivablesPage] = useState(0)
  const [includeVoided, setIncludeVoided] = useState(false)
  const [paymentsPage, setPaymentsPage] = useState(0)
  const [plansPage, setPlansPage] = useState(0)
  const [clientSearch, setClientSearch] = useState('')
  const deferredClientSearch = useDeferredValue(clientSearch)
  const [clientPage, setClientPage] = useState(0)
  const [formMode, setFormMode] = useState<'charge' | 'payment' | 'plan' | null>(null)
  const [receivableForm, setReceivableForm] = useState(RECEIVABLE_FORM)
  const [paymentForm, setPaymentForm] = useState(PAYMENT_FORM)
  const [planForm, setPlanForm] = useState(PLAN_FORM)
  const [generationPeriod, setGenerationPeriod] = useState(BUSINESS_DATE.slice(0, 7))
  const [importFile, setImportFile] = useState<File | null>(null)
  const [preview, setPreview] = useState<ImportPreview | null>(null)

  const summaryQuery = useQuery<CollectionSummary>({ queryKey: ['collections-summary'], queryFn: () => collectionsApi.summary().then((response) => response.data) })
  const receivablesQuery = useQuery<PaginatedResult<Receivable>>({ queryKey: ['receivables', { status, page: receivablesPage }], queryFn: () => collectionsApi.listReceivables({ status: status || undefined, page: receivablesPage, limit: PAGE_SIZE }).then((response) => response.data) })
  const paymentsQuery = useQuery<PaginatedResult<CollectionPayment>>({ queryKey: ['payments', { page: paymentsPage, includeVoided }], queryFn: () => collectionsApi.listPayments({ page: paymentsPage, limit: PAGE_SIZE, includeVoided }).then((response) => response.data) })
  const plansQuery = useQuery<PaginatedResult<RecurringCharge>>({ queryKey: ['recurring-charges', { page: plansPage }], queryFn: () => collectionsApi.listRecurring({ page: plansPage, limit: PAGE_SIZE }).then((response) => response.data) })
  const clientsQuery = useQuery<PaginatedResult<Client>>({ queryKey: ['clients', 'collection-picker', { search: deferredClientSearch, page: clientPage }], queryFn: () => clientsApi.list({ search: deferredClientSearch || undefined, page: clientPage, limit: 20, status: 'ACTIVE' }).then((response) => response.data), enabled: Boolean(formMode) })

  const refresh = () => { queryClient.invalidateQueries({ queryKey: ['collections-summary'] }); queryClient.invalidateQueries({ queryKey: ['receivables'] }); queryClient.invalidateQueries({ queryKey: ['payments'] }); queryClient.invalidateQueries({ queryKey: ['recurring-charges'] }); queryClient.invalidateQueries({ queryKey: ['client-summary'] }) }
  const removePayment = useMutation({ mutationFn: (id: string) => collectionsApi.removePayment(id), onSuccess: refresh })
  const changePaymentStatus = useMutation({ mutationFn: ({ id, status }: { id: string; status: 'RECEIVED' | 'VOID' }) => collectionsApi.setPaymentStatus(id, status), onSuccess: refresh })
  const createReceivable = useMutation({ mutationFn: () => collectionsApi.createReceivable({ ...receivableForm, amount: receivableForm.amount }), onSuccess: () => { refresh(); setReceivableForm(RECEIVABLE_FORM); setFormMode(null) } })
  const createPayment = useMutation({ mutationFn: () => collectionsApi.createPayment({ ...paymentForm, amount: paymentForm.amount }), onSuccess: () => { refresh(); setPaymentForm(PAYMENT_FORM); setFormMode(null) } })
  const createPlan = useMutation({ mutationFn: () => collectionsApi.createRecurring({ ...planForm, amount: planForm.amount, dayOfMonth: Number(planForm.dayOfMonth) }), onSuccess: () => { refresh(); setPlanForm(PLAN_FORM); setFormMode(null) } })
  const previewImport = useMutation({ mutationFn: (file: File) => collectionsApi.import(file, false), onSuccess: (response) => setPreview(response.data as ImportPreview) })
  const commitImport = useMutation({ mutationFn: () => collectionsApi.import(importFile!, true), onSuccess: () => { refresh(); setPreview(null); setImportFile(null); setView('receivables') } })
  const generateRecurring = useMutation({ mutationFn: () => collectionsApi.generateRecurring(generationPeriod), onSuccess: refresh })
  const exportReceivables = useMutation({
    mutationFn: () => collectionsApi.exportReceivables({ status: status || undefined }),
    onSuccess: (response) => {
      const disposition = response.headers['content-disposition'] as string | undefined
      const fileName = disposition?.match(/filename\*?=(?:UTF-8''|"?)([^";]+)/i)?.[1]
      const url = URL.createObjectURL(response.data)
      const anchor = window.document.createElement('a')
      anchor.href = url
      anchor.download = fileName ? decodeURIComponent(fileName.replace(/"/g, '')) : 'cuentas-por-cobrar.csv'
      anchor.click()
      URL.revokeObjectURL(url)
    },
  })

  const pyg = summaryQuery.data?.currencies.find((item) => item.currency === 'PYG') ?? summaryQuery.data?.currencies[0]
  const clients = clientsQuery.data?.items ?? []
  const clientPickerProps = { clients, data: clientsQuery.data, search: clientSearch, setSearch: (value: string) => { setClientSearch(value); setClientPage(0) }, page: clientPage, setPage: setClientPage, loading: clientsQuery.isLoading }
  const generationResult = generateRecurring.data?.data as { generated: number; skipped: number } | undefined

  return <PageFrame><PageHeader eyebrow="Cuenta corriente" title="Gestión de cobranzas" description="Honorarios, cargos, pagos y vencimientos; cada moneda se mantiene separada." action={<div className="flex flex-wrap gap-2"><button type="button" className="btn-secondary" disabled={exportReceivables.isPending} onClick={() => exportReceivables.mutate()}><Download size={15} /> {exportReceivables.isPending ? 'Exportando…' : 'Exportar CSV'}</button>{canManage ? <button type="button" className="btn-secondary" onClick={() => { setView('import'); fileRef.current?.click() }}><Upload size={15} /> Importar</button> : null}{canWrite ? <button type="button" className="btn-primary" onClick={() => setFormMode('charge')}><Plus size={15} /> Nuevo cargo</button> : null}<input ref={fileRef} type="file" accept=".xlsx,.csv" className="sr-only" onChange={(event) => { const file = event.target.files?.[0]; if (file) { setImportFile(file); previewImport.mutate(file) } }} /></div>} />

    {summaryQuery.isError ? <ErrorState message={getErrorMessage(summaryQuery.error)} retry={() => summaryQuery.refetch()} /> : <section className="grid overflow-hidden rounded-xl border border-[var(--line)] bg-[var(--line)] sm:grid-cols-2 xl:grid-cols-4"><LedgerMetric label="Facturado" value={pyg?.billed} currency={pyg?.currency} /><LedgerMetric label="Aplicado" value={pyg?.applied} currency={pyg?.currency} tone="success" /><LedgerMetric label="Saldo pendiente" value={pyg?.outstanding} currency={pyg?.currency} tone={isPositiveDecimal(pyg?.outstanding) ? 'warning' : undefined} /><LedgerMetric label="Cuentas vencidas" value={summaryQuery.data?.overdueCount ?? 0} plain tone={(summaryQuery.data?.overdueCount ?? 0) > 0 ? 'danger' : 'success'} /></section>}

    <nav className="flex gap-1 overflow-x-auto border-b border-[var(--line)]" aria-label="Vistas de cobranzas">{([['receivables', 'Cuentas por cobrar'], ['payments', 'Pagos'], ['plans', 'Planes mensuales'], ['import', 'Importar']] as const).filter(([id]) => id !== 'import' || canManage).map(([id, label]) => <button type="button" key={id} onClick={() => setView(id)} className={clsx('shrink-0 border-b-2 px-4 py-3 text-xs font-bold', view === id ? 'border-[var(--brand-blue)] text-[var(--brand-navy)] dark:text-[var(--brand-blue)]' : 'border-transparent text-[var(--ink-tertiary)]')}>{label}</button>)}</nav>

    {formMode === 'charge' ? <EntryForm title="Registrar cargo" error={createReceivable.error} cancel={() => setFormMode(null)} save={() => createReceivable.mutate()} saving={createReceivable.isPending} disabled={!receivableForm.companyId || !receivableForm.description || !receivableForm.amount || !receivableForm.dueDate}><ClientSelect value={receivableForm.companyId} {...clientPickerProps} onChange={(companyId) => setReceivableForm((current) => ({ ...current, companyId }))} /><Field label="Concepto"><input className="ctrl-input" value={receivableForm.description} onChange={(event) => setReceivableForm((current) => ({ ...current, description: event.target.value }))} /></Field><Field label="Período"><input type="month" className="ctrl-input" value={receivableForm.periodKey} onChange={(event) => setReceivableForm((current) => ({ ...current, periodKey: event.target.value }))} /></Field><Field label="Importe"><input type="number" min="1" className="ctrl-input" value={receivableForm.amount} onChange={(event) => setReceivableForm((current) => ({ ...current, amount: event.target.value }))} /></Field><Field label="Vencimiento"><input type="date" className="ctrl-input" value={receivableForm.dueDate} onChange={(event) => setReceivableForm((current) => ({ ...current, dueDate: event.target.value }))} /></Field><Field label="Referencia"><input className="ctrl-input" value={receivableForm.reference} onChange={(event) => setReceivableForm((current) => ({ ...current, reference: event.target.value }))} /></Field></EntryForm> : null}
    {formMode === 'payment' ? <EntryForm title="Registrar pago" error={createPayment.error} cancel={() => setFormMode(null)} save={() => createPayment.mutate()} saving={createPayment.isPending} disabled={!paymentForm.companyId || !paymentForm.amount}><ClientSelect value={paymentForm.companyId} {...clientPickerProps} onChange={(companyId) => setPaymentForm((current) => ({ ...current, companyId }))} /><Field label="Importe"><input type="number" min="1" className="ctrl-input" value={paymentForm.amount} onChange={(event) => setPaymentForm((current) => ({ ...current, amount: event.target.value }))} /></Field><Field label="Fecha"><input type="date" className="ctrl-input" value={paymentForm.paidAt} onChange={(event) => setPaymentForm((current) => ({ ...current, paidAt: event.target.value }))} /></Field><Field label="Medio"><select className="ctrl-input" value={paymentForm.method} onChange={(event) => setPaymentForm((current) => ({ ...current, method: event.target.value }))}><option value="TRANSFERENCIA">Transferencia</option><option value="EFECTIVO">Efectivo</option><option value="CHEQUE">Cheque</option><option value="OTRO">Otro</option></select></Field><Field label="Referencia"><input className="ctrl-input" value={paymentForm.reference} onChange={(event) => setPaymentForm((current) => ({ ...current, reference: event.target.value }))} /></Field></EntryForm> : null}
    {formMode === 'plan' ? <EntryForm title="Nuevo plan recurrente" error={createPlan.error} cancel={() => setFormMode(null)} save={() => createPlan.mutate()} saving={createPlan.isPending} disabled={!planForm.companyId || !planForm.name || !planForm.amount}><ClientSelect value={planForm.companyId} {...clientPickerProps} onChange={(companyId) => setPlanForm((current) => ({ ...current, companyId }))} /><Field label="Nombre"><input className="ctrl-input" value={planForm.name} onChange={(event) => setPlanForm((current) => ({ ...current, name: event.target.value }))} /></Field><Field label="Importe"><input type="number" min="1" className="ctrl-input" value={planForm.amount} onChange={(event) => setPlanForm((current) => ({ ...current, amount: event.target.value }))} /></Field><Field label="Día de vencimiento"><input type="number" min="1" max="28" className="ctrl-input" value={planForm.dayOfMonth} onChange={(event) => setPlanForm((current) => ({ ...current, dayOfMonth: event.target.value }))} /></Field><Field label="Inicio"><input type="date" className="ctrl-input" value={planForm.startDate} onChange={(event) => setPlanForm((current) => ({ ...current, startDate: event.target.value }))} /></Field></EntryForm> : null}

    {view === 'receivables' ? <ReceivablesView query={receivablesQuery} search={search} setSearch={setSearch} status={status} setStatus={(value) => { setStatus(value); setReceivablesPage(0) }} canWrite={canWrite} onPayment={() => setFormMode('payment')} page={receivablesPage} setPage={setReceivablesPage} /> : null}
    {view === 'payments' ? <PaymentsView includeVoided={includeVoided} setIncludeVoided={(value) => { setIncludeVoided(value); setPaymentsPage(0) }} canManage={canManage} busy={removePayment.isPending || changePaymentStatus.isPending} error={removePayment.error || changePaymentStatus.error} remove={(id) => removePayment.mutate(id)} changeStatus={(id, status) => changePaymentStatus.mutate({ id, status })} query={paymentsQuery} canWrite={canWrite} onNew={() => setFormMode('payment')} page={paymentsPage} setPage={setPaymentsPage} /> : null}
    {view === 'plans' ? <PlansView query={plansQuery} onNew={() => setFormMode('plan')} canManage={canManage} generationPeriod={generationPeriod} setGenerationPeriod={setGenerationPeriod} generate={() => generateRecurring.mutate()} generating={generateRecurring.isPending} result={generationResult} error={generateRecurring.error} page={plansPage} setPage={setPlansPage} /> : null}
    {view === 'import' ? <ImportView file={importFile} preview={preview} previewing={previewImport.isPending} committing={commitImport.isPending} error={previewImport.error || commitImport.error} choose={(file) => { setImportFile(file); previewImport.mutate(file) }} confirm={() => commitImport.mutate()} /> : null}
  </PageFrame>
}

function LedgerMetric({ label, value, currency = 'PYG', tone, plain }: { label: string; value?: string | number; currency?: string; tone?: 'danger' | 'success' | 'warning'; plain?: boolean }) { return <div className="bg-[var(--paper)] p-5"><p className="text-[10px] font-bold uppercase tracking-[.08em] text-[var(--ink-muted)]">{label}</p><p className={clsx('mt-2 font-mono text-xl font-bold tabular-nums text-[var(--ink-primary)]', tone === 'danger' && 'text-[var(--danger)]', tone === 'success' && 'text-[var(--success)]', tone === 'warning' && 'text-[var(--warning)]')}>{plain ? value ?? 0 : formatMoney(value, currency)}</p></div> }
/** Hace clicable toda la fila para abrir el legajo, sin interferir con enlaces ni botones. */
function openClientRow(router: ReturnType<typeof useRouter>, clientId?: string | null) {
  if (!clientId) return {}
  return {
    className: 'cursor-pointer hover:bg-[var(--paper-soft)]',
    onClick: (event: React.MouseEvent<HTMLTableRowElement>) => {
      if ((event.target as HTMLElement).closest('a, button, input, select, label')) return
      if (event.ctrlKey || event.metaKey) window.open(`/clients/${clientId}`, '_blank')
      else router.push(`/clients/${clientId}`)
    },
  }
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-1.5 block text-[11px] font-bold text-[var(--ink-secondary)]">{label}</span>{children}</label> }
function ClientSelect({ value, clients, data, search, setSearch, page, setPage, loading, onChange }: { value: string; clients: Client[]; data?: PaginatedResult<Client>; search: string; setSearch: (value: string) => void; page: number; setPage: React.Dispatch<React.SetStateAction<number>>; loading: boolean; onChange: (value: string) => void }) { return <div className="space-y-2 sm:col-span-2"><Field label="Buscar cliente"><span className="relative block"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--ink-muted)]" /><input className="ctrl-input pl-9" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Nombre, RUC o teléfono…" /></span></Field><Field label="Cliente"><select className="ctrl-input" value={value} disabled={loading} onChange={(event) => onChange(event.target.value)}><option value="">{loading ? 'Buscando…' : 'Seleccionar cliente…'}</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}{client.ruc ? ` · ${client.ruc}${client.dv ? `-${client.dv}` : ''}` : ''}</option>)}</select></Field>{data && data.totalPages > 1 ? <div className="flex items-center justify-between text-[10px] font-semibold text-[var(--ink-muted)]"><span>{data.total} resultados</span><span className="flex gap-1"><button type="button" className="rounded border border-[var(--line)] p-1" disabled={page <= 0} onClick={() => setPage((current) => Math.max(0, current - 1))} aria-label="Clientes anteriores"><ChevronLeft size={13} /></button><button type="button" className="rounded border border-[var(--line)] p-1" disabled={page + 1 >= data.totalPages} onClick={() => setPage((current) => current + 1)} aria-label="Clientes siguientes"><ChevronRight size={13} /></button></span></div> : null}</div> }
function EntryForm({ title, children, error, cancel, save, saving, disabled }: { title: string; children: React.ReactNode; error: unknown; cancel: () => void; save: () => void; saving: boolean; disabled: boolean }) { return <SectionPanel title={title}><div className="grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-3">{children}</div><div className="flex flex-col gap-3 border-t border-[var(--line-soft)] px-5 py-4 sm:flex-row sm:items-center sm:justify-between">{error ? <p className="text-xs font-semibold text-[var(--danger)]">{getErrorMessage(error, 'No pudimos guardar el movimiento.')}</p> : <span />}<div className="flex gap-2"><button type="button" className="btn-secondary" onClick={cancel}>Cancelar</button><button type="button" className="btn-primary" disabled={disabled || saving} onClick={save}>{saving ? 'Guardando…' : 'Guardar'}</button></div></div></SectionPanel> }

function ReceivablesView({ query, search, setSearch, status, setStatus, canWrite, onPayment, page, setPage }: { query: UseQueryResult<PaginatedResult<Receivable>>; search: string; setSearch: (value: string) => void; status: string; setStatus: (value: string) => void; canWrite: boolean; onPayment: () => void; page: number; setPage: React.Dispatch<React.SetStateAction<number>> }) {
  const router = useRouter()
  const items = useMemo(() => { const term = search.trim().toLowerCase(); if (!term) return query.data?.items ?? []; return (query.data?.items ?? []).filter((item) => [item.company?.name, item.company?.ruc, item.description, item.reference].some((value) => value?.toLowerCase().includes(term))) }, [query.data?.items, search])
  if (query.isLoading) return <LoadingState />
  if (query.isError) return <ErrorState message={getErrorMessage(query.error)} retry={() => query.refetch()} />
  return <SectionPanel title="Cuentas por cobrar" action={canWrite ? <button type="button" className="btn-secondary" onClick={onPayment}><Plus size={14} /> Registrar pago</button> : undefined}><div className="grid gap-3 border-b border-[var(--line-soft)] p-3 sm:grid-cols-[minmax(0,1fr)_9rem]"><label className="relative block w-full min-w-0"><Search size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[var(--ink-muted)]" /><input className="ctrl-input !min-h-11 w-full pl-10 text-sm" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar por cliente, RUC, descripción o referencia…" /></label><select className="ctrl-input !min-h-11 w-full" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Todos los estados</option><option value="OVERDUE">Vencidos</option><option value="PENDING">Pendientes</option><option value="PARTIAL">Parciales</option><option value="PAID">Pagados</option><option value="VOID">Anulados</option></select></div>{items.length ? <div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Cliente</th><th>Concepto</th><th>Vencimiento</th><th>Estado</th><th className="text-right">Importe</th><th className="text-right">Saldo</th></tr></thead><tbody>{items.map((item) => <tr key={item.id} {...openClientRow(router, item.company?.id)}><td>{item.company ? <Link className="font-bold text-[var(--ink-primary)] hover:text-[var(--brand-blue)]" href={`/clients/${item.company.id}`}>{item.company.name}</Link> : '—'}</td><td><p className="font-semibold text-[var(--ink-primary)]">{item.description}</p><p className="mt-0.5 text-[11px] text-[var(--ink-tertiary)]">{item.periodKey || item.reference || ''}</p></td><td className={item.status === 'OVERDUE' ? 'font-bold text-[var(--danger)]' : ''}>{formatDate(item.dueDate)}</td><td><StatusPill tone={item.status === 'PAID' ? 'success' : item.status === 'OVERDUE' ? 'danger' : 'warning'}>{RECEIVABLE_LABELS[item.status] ?? item.status}</StatusPill></td><td className="text-right font-mono tabular-nums">{formatMoney(item.amount, item.currency)}</td><td className="text-right font-mono font-bold tabular-nums text-[var(--ink-primary)]">{formatMoney(item.outstanding, item.currency)}</td></tr>)}</tbody></table></div> : <EmptyState title="Sin movimientos" description="No hay cargos que coincidan con los filtros." />}<Pager data={query.data} page={page} setPage={setPage} label="cargos" /></SectionPanel>
}

function PaymentsView({ query, canWrite, onNew, page, setPage, canManage, includeVoided, setIncludeVoided, busy, error, remove, changeStatus }: {
  query: UseQueryResult<PaginatedResult<CollectionPayment>>; canWrite: boolean; onNew: () => void; page: number; setPage: React.Dispatch<React.SetStateAction<number>>;
  canManage: boolean; includeVoided: boolean; setIncludeVoided: (value: boolean) => void; busy: boolean; error: unknown; remove: (id: string) => void; changeStatus: (id: string, status: 'RECEIVED' | 'VOID') => void;
}) {
  const router = useRouter()
  if (query.isLoading) return <LoadingState />
  if (query.isError) return <ErrorState message={getErrorMessage(query.error)} retry={() => query.refetch()} />
  return <SectionPanel title="Pagos registrados" action={canWrite ? <button type="button" className="btn-primary" onClick={onNew}><Plus size={14} /> Registrar pago</button> : undefined}>
    <div className="space-y-2 p-4"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={includeVoided} onChange={(e) => setIncludeVoided(e.target.checked)} /> Mostrar pagos anulados</label><p className="text-xs text-[var(--ink-tertiary)]">Eliminar anula el pago y revierte sus aplicaciones; conserva el historial.</p>{error ? <p role="alert" className="text-sm text-[var(--danger)]">{getErrorMessage(error)}</p> : null}</div>
    {query.data?.items.length ? <div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Fecha</th><th>Cliente</th><th>Medio / Referencia</th><th>Estado</th><th className="text-right">Importe</th><th>Acciones</th></tr></thead><tbody>{query.data.items.map((payment) => <tr key={payment.id} {...openClientRow(router, payment.company?.id)}>
      <td>{formatDate(payment.paidAt)}</td><td>{payment.company?.name || '—'}</td><td>{payment.method || '—'}<p className="text-xs">{payment.reference || '—'}</p></td>
      <td>{canManage ? <select aria-label="Estado del pago" className="ctrl-input" disabled={busy} value={payment.voidedAt ? 'VOID' : 'RECEIVED'} onChange={(e) => { if (confirm('¿Cambiar el estado del pago? Se actualizarán los saldos de los cargos aplicados.')) changeStatus(payment.id, e.target.value as 'RECEIVED' | 'VOID') }}><option value="RECEIVED">Recibido</option><option value="VOID">Anulado</option></select> : <StatusPill tone={payment.voidedAt ? 'warning' : 'success'}>{payment.voidedAt ? 'Anulado' : 'Recibido'}</StatusPill>}</td>
      <td className="text-right font-mono font-bold">{formatMoney(payment.amount, payment.currency)}</td>
      <td><div className="flex flex-wrap gap-2"><PaymentSummaryButton clientId={payment.companyId} />{canManage && !payment.voidedAt ? <button type="button" className="btn-secondary text-[var(--danger)]" disabled={busy} onClick={() => { if (confirm('¿Eliminar este pago? Se anulará y se recalculará el saldo del cliente.')) remove(payment.id) }}>Eliminar pago</button> : null}</div></td>
    </tr>)}</tbody></table></div> : <EmptyState title="Sin pagos registrados" description="Los pagos manuales e importados aparecerán en este historial." />}
    <Pager data={query.data} page={page} setPage={setPage} label="pagos" />
  </SectionPanel>
}

function PlansView({ query, onNew, canManage, generationPeriod, setGenerationPeriod, generate, generating, result, error, page, setPage }: { query: UseQueryResult<PaginatedResult<RecurringCharge>>; onNew: () => void; canManage: boolean; generationPeriod: string; setGenerationPeriod: (value: string) => void; generate: () => void; generating: boolean; result?: { generated: number; skipped: number }; error: unknown; page: number; setPage: React.Dispatch<React.SetStateAction<number>> }) { const router = useRouter(); if (query.isLoading) return <LoadingState />; if (query.isError) return <ErrorState message={getErrorMessage(query.error)} retry={() => query.refetch()} />; return <SectionPanel title="Planes recurrentes" description="Honorarios que se generan una sola vez por período, incluso si repetís la acción." action={canManage ? <button type="button" className="btn-primary" onClick={onNew}><Plus size={14} /> Nuevo plan</button> : undefined}>{canManage ? <div className="flex flex-col gap-3 border-b border-[var(--line-soft)] p-4 sm:flex-row sm:items-end"><Field label="Período a generar"><input type="month" className="ctrl-input" value={generationPeriod} onChange={(event) => setGenerationPeriod(event.target.value)} /></Field><button type="button" className="btn-secondary" disabled={!generationPeriod || generating} onClick={generate}>{generating ? 'Generando…' : 'Generar honorarios'}</button>{result ? <p className="pb-2 text-xs font-semibold text-[var(--success)]">{result.generated} generados · {result.skipped} ya existentes</p> : null}{error ? <p className="pb-2 text-xs font-semibold text-[var(--danger)]">{getErrorMessage(error, 'No pudimos generar los honorarios.')}</p> : null}</div> : null}{query.data?.items.length ? <div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Cliente</th><th>Concepto</th><th>Frecuencia</th><th>Día</th><th className="text-right">Importe</th></tr></thead><tbody>{query.data.items.map((plan) => <tr key={plan.id} {...openClientRow(router, plan.company?.id)}><td>{plan.company?.name || '—'}</td><td className="font-semibold text-[var(--ink-primary)]">{plan.name}</td><td><StatusPill tone="brand">{FREQUENCY_LABELS[plan.frequency] ?? plan.frequency}</StatusPill></td><td>{plan.dayOfMonth}</td><td className="text-right font-mono font-bold">{formatMoney(plan.amount, plan.currency)}</td></tr>)}</tbody></table></div> : <EmptyState title="Sin planes recurrentes" description="Creá planes mensuales para automatizar la generación de honorarios." />}<Pager data={query.data} page={page} setPage={setPage} label="planes" /></SectionPanel> }

function Pager({ data, page, setPage, label }: { data?: PaginatedResult<unknown>; page: number; setPage: React.Dispatch<React.SetStateAction<number>>; label: string }) { if (!data || data.totalPages <= 1) return null; return <div className="flex flex-col gap-3 border-t border-[var(--line-soft)] px-4 py-3 text-xs text-[var(--ink-tertiary)] sm:flex-row sm:items-center sm:justify-between"><p><strong className="text-[var(--ink-primary)]">{data.total}</strong> {label} · página {data.page + 1} de {data.totalPages}</p><div className="flex gap-2"><button type="button" className="btn-secondary" disabled={page <= 0} onClick={() => setPage((current) => Math.max(0, current - 1))}><ChevronLeft size={14} /> Anterior</button><button type="button" className="btn-secondary" disabled={page + 1 >= data.totalPages} onClick={() => setPage((current) => current + 1)}>Siguiente <ChevronRight size={14} /></button></div></div> }

function ImportView({ file, preview, previewing, committing, error, choose, confirm }: { file: File | null; preview: ImportPreview | null; previewing: boolean; committing: boolean; error: unknown; choose: (file: File) => void; confirm: () => void }) { return <SectionPanel title="Importar cobranzas" description="Primero validamos; para confirmar reenviamos el mismo archivo sin guardar copias temporales."><div className="p-5">{!file ? <div className="state-panel border-dashed"><FileSpreadsheet size={32} className="text-[var(--brand-blue)]" /><p className="font-bold text-[var(--ink-primary)]">Seleccioná una planilla .xlsx o .csv</p><label className="btn-primary cursor-pointer"><Upload size={15} /> Elegir archivo<input type="file" accept=".xlsx,.csv" className="sr-only" onChange={(event) => { const selected = event.target.files?.[0]; if (selected) choose(selected) }} /></label></div> : <div className="space-y-5"><div><p className="font-bold text-[var(--ink-primary)]">{file.name}</p><p className="mt-1 text-xs text-[var(--ink-tertiary)]">{previewing ? 'Validando…' : `${preview?.valid ?? 0} válidos · ${preview?.invalid ?? 0} con errores`}</p></div>{preview ? <><div className="grid gap-px overflow-hidden rounded-lg border border-[var(--line)] bg-[var(--line)] sm:grid-cols-3"><ImportCount icon={CheckCircle2} label="Válidas" count={preview.valid} tone="success" /><ImportCount icon={AlertTriangle} label="Con errores" count={preview.invalid} tone="danger" /><ImportCount icon={FileSpreadsheet} label="Total" count={preview.total} tone="warning" /></div><ImportRowsTable preview={preview} /></> : null}<div className="flex justify-end"><button type="button" className="btn-primary" disabled={!preview?.valid || Boolean(preview.invalid) || committing} onClick={confirm}>{committing ? 'Importando…' : preview?.invalid ? 'Corregí las filas con errores' : `Confirmar ${preview?.valid ?? 0} movimientos`}</button></div></div>}{error ? <p className="mt-4 text-xs font-semibold text-[var(--danger)]">{getErrorMessage(error, 'No pudimos procesar la planilla.')}</p> : null}</div></SectionPanel> }

function ImportRowsTable({ preview }: { preview: ImportPreview }) {
  const invalidRows = preview.rows.filter((row) => row.errors.length > 0)
  const validRows = preview.rows.filter((row) => row.errors.length === 0).slice(0, 20)
  const rows = [...invalidRows, ...validRows]
  if (!rows.length) return null
  return <div><div className="mb-2 flex flex-wrap items-center justify-between gap-2"><p className="text-xs font-bold text-[var(--ink-secondary)]">Validación por fila</p><p className="text-[10px] text-[var(--ink-muted)]">Todas las filas con error y hasta 20 válidas</p></div><div className="max-h-[420px] overflow-auto rounded-lg border border-[var(--line)]"><table className="data-table"><thead className="sticky top-0 z-10 bg-[var(--paper)]"><tr><th>Fila</th><th>Tipo / RUC</th><th>Concepto</th><th className="text-right">Monto</th><th>Resultado</th></tr></thead><tbody>{rows.map((row) => <tr key={`${row.rowNumber}-${row.type}`} className="[content-visibility:auto]"><td className="font-mono text-xs">{row.rowNumber}</td><td><p className="text-xs font-bold text-[var(--ink-primary)]">{row.type === 'PAYMENT' ? 'Pago' : 'Cargo'}</p><p className="mt-0.5 text-[10px] text-[var(--ink-tertiary)]">RUC {row.ruc || '—'}</p></td><td className="max-w-56"><p className="truncate text-xs text-[var(--ink-secondary)]">{row.description || (row.type === 'PAYMENT' ? 'Aplicación de pago' : '—')}</p></td><td className="whitespace-nowrap text-right font-mono text-xs font-bold">{formatImportAmount(row)}</td><td>{row.errors.length ? <div className="space-y-1">{row.errors.map((message) => <p key={message} className="text-xs font-semibold text-[var(--danger)]">{message}</p>)}</div> : <StatusPill tone="success">Válida</StatusPill>}</td></tr>)}</tbody></table></div>{preview.valid > validRows.length ? <p className="mt-2 text-[10px] text-[var(--ink-muted)]">{preview.valid - validRows.length} filas válidas adicionales no se muestran en esta vista previa.</p> : null}</div>
}
function ImportCount({ icon: Icon, label, count, tone }: { icon: typeof CheckCircle2; label: string; count: number; tone: 'success' | 'danger' | 'warning' }) { return <div className="flex items-center gap-3 bg-[var(--paper)] p-4"><Icon size={18} className={tone === 'success' ? 'text-[var(--success)]' : tone === 'danger' ? 'text-[var(--danger)]' : 'text-[var(--warning)]'} /><div><p className="font-mono text-lg font-bold tabular-nums text-[var(--ink-primary)]">{count}</p><p className="text-[10px] font-bold uppercase tracking-wide text-[var(--ink-muted)]">{label}</p></div></div> }
